### ISSUE TITLE
build: EditorSystem uses renamed GetSDLWindow method — master build broken

### ISSUE THREAD

**Issue by Junseo9** [Junseo9/Raphael#24]
## Description

`EditorSystem::InitImGui()` calls `m_Window->GetSDLWindow()` on lines 148 and 152, but this method was renamed to `GetSDLWindowRaw()` (returning `void*` instead of `SDL_Window*`) in commit `48ae1e5` ("Remove duplicate SDL event polling from Window, subscribe to EventBus instead"), merged via PR #6.

The editor module was added earlier via PR #4 (`feature/editor`), which used the old method name. When PR #6 merged the rename, `EditorSystem.cpp` was not updated — a semantic merge conflict that was not caught.

**This breaks the master branch build.**

## Build Error

```
engine/editor/src/EditorSystem.cpp:148:37: error: 'class raph::Window' has no member named 'GetSDLWindow'; did you mean 'GetSDLWindowRaw'?
  148 |         if (!m_Window || !m_Window->GetSDLWindow()) {

engine/editor/src/EditorSystem.cpp:152:48: error: 'class raph::Window' has no member named 'GetSDLWindow'; did you mean 'GetSDLWindowRaw'?
  152 |         ImGui_ImplSDL3_InitForVulkan(m_Window->GetSDLWindow());
```

## Location

- **File(s)**: `engine/editor/src/EditorSystem.cpp` lines 148, 152
- **Module**: `engine/editor`
- **Root Cause**: `engine/windowing/include/raphael/windowing/Window.h` line 76 — `GetSDLWindow()` renamed to `GetSDLWindowRaw()` in commit `48ae1e5`

## Current Behavior

Build fails with 2 compilation errors. `ninja: build stopped: cannot make progress due to previous errors.`

## Expected Behavior

`EditorSystem.cpp` should call `GetSDLWindowRaw()` and cast the `void*` return to `SDL_Window*` (since `ImGui_ImplSDL3_InitForVulkan` expects `SDL_Window*`).

## Possible Solution

Replace both occurrences:

```cpp
// Line 148: null check
if (!m_Window || !m_Window->GetSDLWindowRaw()) {

// Line 152: pass to ImGui (needs cast since GetSDLWindowRaw returns void*)
ImGui_ImplSDL3_InitForVulkan(static_cast<SDL_Window*>(m_Window->GetSDLWindowRaw()));
```

## Environment

- OS: Windows 10
- Compiler: GCC (MinGW-w64) via MSYS2
- CMake: 3.20+
- Build Type: Release
